// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// centerdata
arma::mat centerdata(arma::mat X);
RcppExport SEXP _ShrinkCovMat_centerdata(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(centerdata(X));
    return rcpp_result_gen;
END_RCPP
}
// trace_stats_uncentered
arma::vec trace_stats_uncentered(arma::mat X);
RcppExport SEXP _ShrinkCovMat_trace_stats_uncentered(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(trace_stats_uncentered(X));
    return rcpp_result_gen;
END_RCPP
}
// trace_stats_centered
arma::vec trace_stats_centered(arma::mat X);
RcppExport SEXP _ShrinkCovMat_trace_stats_centered(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(trace_stats_centered(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ShrinkCovMat_centerdata", (DL_FUNC) &_ShrinkCovMat_centerdata, 1},
    {"_ShrinkCovMat_trace_stats_uncentered", (DL_FUNC) &_ShrinkCovMat_trace_stats_uncentered, 1},
    {"_ShrinkCovMat_trace_stats_centered", (DL_FUNC) &_ShrinkCovMat_trace_stats_centered, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ShrinkCovMat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
