# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

centerdata <- function(X) {
    .Call(`_ShrinkCovMat_centerdata`, X)
}

trace_stats_uncentered <- function(X) {
    .Call(`_ShrinkCovMat_trace_stats_uncentered`, X)
}

trace_stats_centered <- function(X) {
    .Call(`_ShrinkCovMat_trace_stats_centered`, X)
}

